server:
  port: 8088
  
spring:
  application:
    name: microservice-consumer

eureka:
  client:
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:6001/eureka
      #Eureka服务器集群
      defaultZone: http://127.0.0.1:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: microservice-consumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址

#可以省略  客户端的基本信息
info:
  app.name: cssl-microservice
  company.name: www.cssl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$